INPUT_FILE_NAME:
  Charges_use: ./Data/Charges_use.csv
  Damages_use: ./Data/Damages_use.csv
  Endorse_use: ./Data/Endorse_use.csv
  Primary_Person_use: ./Data/Primary_Person_use.csv
  Units_use: ./Data/Units_use.csv
  Restrict_use: ./Data/Restrict_use.csv

OUTPUT_FILE_PATH:
  Path1: ./Output1
  Path2: ./Output2
  Path3: ./Output3
  Path4: ./Output4
  Path5: ./Output5
  Path6: ./Output6
  Path7: ./Output7
  Path8: ./Output8

OUTPUT_FILE_FORMAT:
  Format: parquet